name: Fetch Messages from Protect Artshack's Mission Form

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  fetch:
    name: Fetch Messages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Check
        run: |
          jq --version
          curl --version

      - name: fetch
        shell: bash
        run: ./scripts/fetch_community_messages.sh
        env:
          JOTFORM_API_KEY: ${{ secrets.JOTFORM_API_KEY }}

      - name: Commit and Push Changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update messages.json"
          file_pattern: public/messages.json
